# Generated by Django 2.1.2 on 2018-10-12 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucketlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BucketSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Bucketlist')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
                ('genre', models.IntegerField(choices=[(1, 'Tourist Spot'), (2, 'Restaurant'), (3, 'Bar')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='bucketspot',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Spot'),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.City'),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
