# Generated by Django 2.1.2 on 2018-10-16 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Comment')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='spots',
            field=models.ManyToManyField(through='main_app.BucketSpot', to='main_app.Spot'),
        ),
    ]
